name: Verification HTML

on:
 push:

jobs:

 check-html:

  runs-on: self-hosted

  steps:

  - uses: actions/checkout@v4

  - name: Vérifier index.html
    run: |
      if [ -f index.html ]; then
        echo "Fichier HTML OK"
      else
        echo "index.html manquant"
        exit 1
      fi
